directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: pl.lt.videodownloader
productName: Video Downloader
copyright: Copyright © 2018 Robert Orłowski
win:
  icon: public/assets/app.png
  publisherName: Robert Orłowski
electronVersion: 2.0.15
